title: 피카츄의 수학노트
description: about math
theme: just-the-docs

url: https://realdavid06.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
color_scheme: light
